[package]
name = "bern-test-macros"
version = "0.1.0"
authors = ["Stefan Lüthi <stefan.luethi@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.20"
quote = "1.0.7"
syn = { version = "1.0.40", features = ["extra-traits", "full"] }